# Image upload
Kochan_froala_editor_upload_image:
    path: /upload_image
    controller: Kochan\FroalaEditorBundle\Controller\MediaController::uploadImage

Kochan_froala_editor_delete_image:
    path: /delete_image
    controller: Kochan\FroalaEditorBundle\Controller\MediaController::deleteImage

Kochan_froala_editor_load_images:
    path: /load_images
    controller: Kochan\FroalaEditorBundle\Controller\MediaController::loadImages

# File upload
Kochan_froala_editor_upload_file:
    path: /upload_file
    controller: Kochan\FroalaEditorBundle\Controller\MediaController::uploadFile

# Video upload
Kochan_froala_editor_upload_video:
    path: /upload_video
    controller: Kochan\FroalaEditorBundle\Controller\MediaController::uploadVideo
